# Generated by Django 6.0.6 on 2026-07-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldier_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('rank', models.CharField(choices=[('General', 'General'), ('Colonel', 'Colonel'), ('Major', 'Major'), ('Captain', 'Captain'), ('Lieutenant', 'Lieutenant'), ('Soldier', 'Soldier')], max_length=20)),
                ('posting', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('On Duty', 'On Duty'), ('Leave', 'Leave')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='soldiers/')),
            ],
        ),
    ]
